spring:
  application:
    name: __DDD_PROJECT_NAME__
  datasource:
    url: "jdbc:mysql://xxxxx:3306/xxxxx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
    username: xxxxx
    password: xxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
